name: developers github actions CI
on: 
  pull_request:
    branches:
      - develop

jobs:
  before_merge_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - run: npm ci




